<?php

namespace MainBundle\Repository;

/**
 * OffreCovoiturage
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffreCovoiturageRepository extends \Doctrine\ORM\EntityRepository
{


    public function myfindCovoiturageExpirerAll()
    {
        $query = $this->getEntityManager()->createQuery("select v from MainBundle:OffreCovoiturage v where v.nbrPlacesDispo = 0 ");
        return $query->getResult();
    }
}
