offrecovoiturage_index:
    path:     /User/covoiturage
    defaults: { _controller: MainBundle:OffreCovoiturage:index}

offrecovoiturage_new:
    path:     /User/newcovoiturage
    defaults: { _controller: MainBundle:OffreCovoiturage:new }

offrecovoiturage_show:
    path:     /showcovoiturage/{idOffre}
    defaults: { _controller: MainBundle:OffreCovoiturage:show }

offrecovoiturage_delete:
    path:     /delete/{idOffre}
    defaults: { _controller: MainBundle:OffreCovoiturage:delete }

offrecovoiturage_edit:
    path:     /{idOffre}/edit
    defaults: { _controller: MainBundle:OffreCovoiturage:edit }


main_homepage:
    path:     /admin/dashboard
    defaults: { _controller: MainBundle:Default:index }

admin_User_affiche:
        path:     /admin/UserAffichage
        defaults: { _controller: MainBundle:Utilisateur:index}

main_homepageFront:
    path:     User/indexFront
    defaults: { _controller: MainBundle:Default:indexFront }

admin_User_validation:
        path:     /admin/validerUser/{user}
        defaults: { _controller: MainBundle:Utilisateur:validerUser}

admin_User_delete:
        path:     /admin/deleteUser/{user}
        defaults: { _controller: MainBundle:Utilisateur:delete}

User_Inscription:
        path:     /inscription
        defaults: { _controller: MainBundle:Utilisateur:inscription}

ReclamationCovoiturage_index:
    path:     /User/ReclamationCovoiturage
    defaults: { _controller: MainBundle:Reclamation:newReclamation}

Historique_Covoiturage:
  path:      /User/HistoriqueCovoiturage
  defaults: { _controller: MainBundle:OffreCovoiturage:showHistorique}

ShowReclamationList:
  path:     /User/ShowListReclamation
  defaults: { _controller: MainBundle:Reclamation:showReclamation}

SignalerCovoiturage_index:
    path:     /User/SiganlerCovoiturage
    defaults: { _controller: MainBundle:Reclamation:newSignaler}